/* Der Kanon: Hauptwerke jeder Etappe.
   Ein Werk pro Eintrag mit Verfasser, Jahr, Gebiet und dem, worum es geht.
   Die Zuordnung zur Etappe sagt nicht, wann man ein Werk lesen MUSS, sondern
   ab wann es sinnvoll besprochen werden kann.
   etappe: 1 Grundschule · 2 Unterstufe · 3 Mittelstufe · 4 Oberstufe · 5 Erwachsene */

export const HAUPTWERKE = [
  /* ---------------- Etappe 1–2: Kinder ---------------- */
  { werk:'Die Kinder- und Hausmärchen', autor:'Brüder Grimm', jahr:1812, gebiet:'Literatur', etappe:1,
    worum:'Gesammelte Volksmärchen – Hänsel und Gretel, Rotkäppchen, Aschenputtel.' },
  { werk:'Alice im Wunderland', autor:'Lewis Carroll', jahr:1865, gebiet:'Literatur', etappe:1,
    worum:'Ein Mädchen fällt in einen Kaninchenbau und landet in einer Welt, in der die Logik verrücktspielt.' },
  { werk:'Pinocchio', autor:'Carlo Collodi', jahr:1883, gebiet:'Literatur', etappe:1,
    worum:'Eine Holzpuppe will ein richtiger Junge werden – und lernt dabei, was Ehrlichkeit kostet.' },
  { werk:'Das Dschungelbuch', autor:'Rudyard Kipling', jahr:1894, gebiet:'Literatur', etappe:1,
    worum:'Der Junge Mogli wächst bei Wölfen auf und muss sich zwischen zwei Welten entscheiden.' },
  { werk:'Emil und die Detektive', autor:'Erich Kästner', jahr:1929, gebiet:'Literatur', etappe:1,
    worum:'Ein Junge wird im Zug bestohlen – und eine Kinderbande in Berlin jagt den Dieb.' },
  { werk:'Pippi Langstrumpf', autor:'Astrid Lindgren', jahr:1945, gebiet:'Literatur', etappe:1,
    worum:'Ein Mädchen ohne Eltern, stärker als jeder Erwachsene, das sich an keine Regel hält.' },
  { werk:'Der kleine Prinz', autor:'Antoine de Saint-Exupéry', jahr:1943, gebiet:'Literatur', etappe:2,
    worum:'Ein Pilot trifft in der Wüste einen Jungen von einem anderen Planeten. „Man sieht nur mit dem Herzen gut.“' },
  { werk:'Momo', autor:'Michael Ende', jahr:1973, gebiet:'Literatur', etappe:2,
    worum:'Graue Herren stehlen den Menschen die Zeit – ein Mädchen hält dagegen, indem es zuhört.' },
  { werk:'Die Abenteuer des Tom Sawyer', autor:'Mark Twain', jahr:1876, gebiet:'Literatur', etappe:2,
    worum:'Ein Junge am Mississippi, der Streiche spielt – und Zeuge eines Mordes wird.' },

  /* ---------------- Etappe 3: Mittelstufe ---------------- */
  { werk:'Die Odyssee', autor:'Homer', jahr:-700, gebiet:'Literatur', etappe:3,
    worum:'Zehn Jahre Irrfahrt eines Kriegers nach Hause – Zyklop, Sirenen, Kirke.' },
  { werk:'Romeo und Julia', autor:'William Shakespeare', jahr:1597, gebiet:'Literatur', etappe:3,
    worum:'Zwei Liebende aus verfeindeten Familien – die Feindschaft der Eltern kostet sie das Leben.' },
  { werk:'Wilhelm Tell', autor:'Friedrich Schiller', jahr:1804, gebiet:'Literatur', etappe:3,
    worum:'Ein Schütze muss auf den Apfel auf dem Kopf seines Sohnes zielen – und wird zum Widerstandskämpfer.' },
  { werk:'Im Westen nichts Neues', autor:'Erich Maria Remarque', jahr:1929, gebiet:'Literatur', etappe:3,
    worum:'Junge Soldaten im Ersten Weltkrieg – gegen jede Kriegsbegeisterung geschrieben.' },
  { werk:'Das Tagebuch der Anne Frank', autor:'Anne Frank', jahr:1947, gebiet:'Literatur', etappe:3,
    worum:'Ein Mädchen schreibt zwei Jahre lang im Versteck in Amsterdam, bis es entdeckt wird.' },
  { werk:'Farm der Tiere', autor:'George Orwell', jahr:1945, gebiet:'Literatur', etappe:3,
    worum:'Tiere vertreiben den Bauern – und ihre Anführer werden schlimmer als er.' },
  { werk:'Die Physiker', autor:'Friedrich Dürrenmatt', jahr:1962, gebiet:'Literatur', etappe:3,
    worum:'Ein Physiker flieht in die Irrenanstalt, um seine Entdeckung vor der Welt zu verstecken.' },
  { werk:'Die Verwandlung', autor:'Franz Kafka', jahr:1915, gebiet:'Literatur', etappe:3,
    worum:'Gregor Samsa erwacht als Ungeziefer – und wird für seine Familie zur Last.' },

  /* ---------------- Etappe 4: Oberstufe ---------------- */
  { werk:'Faust. Der Tragödie erster Teil', autor:'Johann Wolfgang von Goethe', jahr:1808, gebiet:'Literatur', etappe:4,
    worum:'Ein Gelehrter wettet seine Seele auf einen einzigen Augenblick, den er festhalten möchte.' },
  { werk:'Woyzeck', autor:'Georg Büchner', jahr:1879, gebiet:'Literatur', etappe:4,
    worum:'Ein armer Soldat wird gedemütigt und zerbricht – das erste Drama über einen Menschen ganz unten.' },
  { werk:'Effi Briest', autor:'Theodor Fontane', jahr:1895, gebiet:'Literatur', etappe:4,
    worum:'Eine junge Frau in einer erstarrten Gesellschaft, die an deren Regeln zugrunde geht.' },
  { werk:'Der Process', autor:'Franz Kafka', jahr:1925, gebiet:'Literatur', etappe:4,
    worum:'Josef K. wird angeklagt, ohne je zu erfahren, weshalb.' },
  { werk:'Schuld und Sühne', autor:'Fjodor Dostojewski', jahr:1866, gebiet:'Literatur', etappe:4,
    worum:'Ein Student tötet eine Pfandleiherin, um zu beweisen, dass er über der Moral steht – und zerbricht daran.' },
  { werk:'1984', autor:'George Orwell', jahr:1949, gebiet:'Literatur', etappe:4,
    worum:'Ein Staat überwacht jeden Gedanken und ändert laufend die Vergangenheit.' },
  { werk:'Schöne neue Welt', autor:'Aldous Huxley', jahr:1932, gebiet:'Literatur', etappe:4,
    worum:'Eine Gesellschaft ohne Leid – erkauft mit dem Verzicht auf Freiheit, Kunst und Wahrheit.' },
  { werk:'Der Fremde', autor:'Albert Camus', jahr:1942, gebiet:'Literatur', etappe:4,
    worum:'Ein Mann tötet ohne Grund und wird vor allem dafür verurteilt, dass er bei der Beerdigung seiner Mutter nicht weinte.' },
  { werk:'Mutter Courage und ihre Kinder', autor:'Bertolt Brecht', jahr:1941, gebiet:'Literatur', etappe:4,
    worum:'Eine Händlerin lebt vom Krieg und verliert an ihn alle drei Kinder.' },

  /* ---------------- Etappe 5: Erwachsene ---------------- */
  { werk:'Don Quijote', autor:'Miguel de Cervantes', jahr:1605, gebiet:'Literatur', etappe:5,
    worum:'Ein Landadeliger liest zu viele Ritterromane und zieht aus, die Welt zu retten – der erste moderne Roman.' },
  { werk:'Moby-Dick', autor:'Herman Melville', jahr:1851, gebiet:'Literatur', etappe:5,
    worum:'Die Jagd eines Kapitäns auf einen weißen Wal – eine Besessenheit, die alle mit in den Abgrund zieht.' },
  { werk:'Der Zauberberg', autor:'Thomas Mann', jahr:1924, gebiet:'Literatur', etappe:5,
    worum:'Sieben Jahre in einem Lungensanatorium, in denen die Zeit und ein ganzes Zeitalter zerfließen.' },
  { werk:'Hundert Jahre Einsamkeit', autor:'Gabriel García Márquez', jahr:1967, gebiet:'Literatur', etappe:5,
    worum:'Sechs Generationen einer Familie in einem erfundenen Dorf – Geschichte als Kreis.' },
  { werk:'Die Göttliche Komödie', autor:'Dante Alighieri', jahr:1321, gebiet:'Literatur', etappe:5,
    worum:'Eine Wanderung durch Hölle, Läuterungsberg und Paradies – das Weltbild des Mittelalters in Versen.' },
  { werk:'Mrs Dalloway', autor:'Virginia Woolf', jahr:1925, gebiet:'Literatur', etappe:5,
    worum:'Ein einziger Tag in London, erzählt aus dem Inneren der Gedanken.' },

  /* ---------------- Philosophie ---------------- */
  { werk:'Der Staat (Politeia)', autor:'Platon', jahr:-375, gebiet:'Philosophie', etappe:4,
    worum:'Was ist Gerechtigkeit? Enthält das Höhlengleichnis: Menschen halten Schatten für die Wirklichkeit.' },
  { werk:'Nikomachische Ethik', autor:'Aristoteles', jahr:-340, gebiet:'Philosophie', etappe:4,
    worum:'Ein gutes Leben entsteht durch Gewohnheit: Tugend liegt in der Mitte zwischen zwei Übertreibungen.' },
  { werk:'Meditationen über die Erste Philosophie', autor:'René Descartes', jahr:1641, gebiet:'Philosophie', etappe:4,
    worum:'Alles wird bezweifelt, bis ein Satz übrig bleibt: Ich denke, also bin ich.' },
  { werk:'Kritik der reinen Vernunft', autor:'Immanuel Kant', jahr:1781, gebiet:'Philosophie', etappe:5,
    worum:'Was können wir überhaupt erkennen? Wir sehen die Welt nie roh, sondern immer durch Raum, Zeit und Begriffe.' },
  { werk:'Der Fürst', autor:'Niccolò Machiavelli', jahr:1532, gebiet:'Philosophie', etappe:5,
    worum:'Wie Macht wirklich funktioniert – nicht wie sie funktionieren sollte.' },
  { werk:'Über die Freiheit', autor:'John Stuart Mill', jahr:1859, gebiet:'Philosophie', etappe:5,
    worum:'Die Freiheit des Einzelnen endet dort, wo sie anderen schadet – sonst nirgends.' },
  { werk:'Also sprach Zarathustra', autor:'Friedrich Nietzsche', jahr:1885, gebiet:'Philosophie', etappe:5,
    worum:'Eine Abrechnung mit überkommenen Werten und die Frage, wer neue setzen kann.' },
  { werk:'Vita activa', autor:'Hannah Arendt', jahr:1958, gebiet:'Philosophie', etappe:5,
    worum:'Die Unterscheidung von Arbeiten, Herstellen und Handeln – und warum nur Handeln politisch ist.' },
  { werk:'Logik der Forschung', autor:'Karl Popper', jahr:1934, gebiet:'Philosophie', etappe:5,
    worum:'Wissenschaft beweist nie endgültig; sie muss sich widerlegbar machen. Sonst ist sie keine.' },
  { werk:'Das andere Geschlecht', autor:'Simone de Beauvoir', jahr:1949, gebiet:'Philosophie', etappe:5,
    worum:'„Man kommt nicht als Frau zur Welt, man wird es.“ Die Rolle als gesellschaftliches Erzeugnis.' },

  /* ---------------- Wissenschaft ---------------- */
  { werk:'Die Elemente', autor:'Euklid', jahr:-300, gebiet:'Wissenschaft', etappe:3,
    worum:'Die gesamte Geometrie aus fünf Grundsätzen abgeleitet – 2000 Jahre lang das meistgelesene Lehrbuch.' },
  { werk:'Über die Umläufe der Himmelskörper', autor:'Nikolaus Kopernikus', jahr:1543, gebiet:'Wissenschaft', etappe:4,
    worum:'Nicht die Erde steht im Mittelpunkt, sondern die Sonne.' },
  { werk:'Principia (Mathematische Grundlagen der Naturphilosophie)', autor:'Isaac Newton', jahr:1687, gebiet:'Wissenschaft', etappe:4,
    worum:'Dieselben Gesetze für den fallenden Apfel und die Planeten – die Geburt der Physik als Wissenschaft.' },
  { werk:'Über die Entstehung der Arten', autor:'Charles Darwin', jahr:1859, gebiet:'Wissenschaft', etappe:3,
    worum:'Arten verändern sich durch natürliche Auslese – niemand plant sie.' },
  { werk:'Versuche über Pflanzenhybriden', autor:'Gregor Mendel', jahr:1866, gebiet:'Wissenschaft', etappe:4,
    worum:'Vererbung folgt einfachen Zahlenverhältnissen – 35 Jahre lang übersehen.' },
  { werk:'Zur Elektrodynamik bewegter Körper', autor:'Albert Einstein', jahr:1905, gebiet:'Wissenschaft', etappe:5,
    worum:'Die spezielle Relativitätstheorie: Zeit und Länge hängen davon ab, wie schnell man sich bewegt.' },
  { werk:'Über berechenbare Zahlen', autor:'Alan Turing', jahr:1936, gebiet:'Wissenschaft', etappe:5,
    worum:'Was kann eine Maschine im Prinzip berechnen – und was grundsätzlich nicht?' },
  { werk:'Eine mathematische Theorie der Kommunikation', autor:'Claude Shannon', jahr:1948, gebiet:'Wissenschaft', etappe:5,
    worum:'Information wird messbar – das Bit. Grundlage jeder digitalen Übertragung.' },
  { werk:'Die Struktur wissenschaftlicher Revolutionen', autor:'Thomas Kuhn', jahr:1962, gebiet:'Wissenschaft', etappe:5,
    worum:'Wissenschaft wächst nicht stetig, sondern in Umbrüchen – der Begriff „Paradigmenwechsel“ stammt hierher.' },
  { werk:'Der stumme Frühling', autor:'Rachel Carson', jahr:1962, gebiet:'Wissenschaft', etappe:4,
    worum:'Die Wirkung von Pestiziden auf die Natur – der Anstoß der modernen Umweltbewegung.' },

  /* ---------------- Musik und Kunst ---------------- */
  { werk:'Das Wohltemperierte Klavier', autor:'Johann Sebastian Bach', jahr:1722, gebiet:'Musik', etappe:3,
    worum:'Präludien und Fugen in allen 24 Tonarten – das Grundbuch der abendländischen Musik.' },
  { werk:'Die Zauberflöte', autor:'Wolfgang Amadeus Mozart', jahr:1791, gebiet:'Musik', etappe:2,
    worum:'Ein Märchen als Oper: Prüfungen, Papageno und die Königin der Nacht.' },
  { werk:'9. Sinfonie', autor:'Ludwig van Beethoven', jahr:1824, gebiet:'Musik', etappe:3,
    worum:'Erste Sinfonie mit Chor; das Finale wurde zur Europahymne. Beethoven war da bereits taub.' },
  { werk:'Le Sacre du Printemps', autor:'Igor Strawinsky', jahr:1913, gebiet:'Musik', etappe:5,
    worum:'Die Uraufführung endete im Tumult – die Rhythmen sprengten alles Gewohnte.' },
  { werk:'Die Sixtinische Decke', autor:'Michelangelo', jahr:1512, gebiet:'Kunst', etappe:3,
    worum:'Vier Jahre auf dem Rücken auf einem Gerüst – die Erschaffung Adams entstand dort.' },
  { werk:'Das Mädchen mit dem Perlenohrring', autor:'Jan Vermeer', jahr:1665, gebiet:'Kunst', etappe:2,
    worum:'Kein Porträt einer bestimmten Person, sondern eine Studie über Licht und Blick.' },
  { werk:'Sternennacht', autor:'Vincent van Gogh', jahr:1889, gebiet:'Kunst', etappe:2,
    worum:'Gemalt aus dem Fenster einer Heilanstalt – der Himmel in Wirbeln.' },
  { werk:'Guernica', autor:'Pablo Picasso', jahr:1937, gebiet:'Kunst', etappe:4,
    worum:'Die Bombardierung einer baskischen Stadt – das bekannteste Antikriegsbild der Moderne.' },
  { werk:'Fontäne (Fountain)', autor:'Marcel Duchamp', jahr:1917, gebiet:'Kunst', etappe:5,
    worum:'Ein umgedrehtes Pissoir als Kunstwerk – die Frage, wer bestimmt, was Kunst ist.' }
];

export const GEBIETE = ['Literatur','Philosophie','Wissenschaft','Musik','Kunst'];

export const ETAPPEN_NAMEN = {
  1:'Grundschule', 2:'Unterstufe', 3:'Mittelstufe', 4:'Oberstufe', 5:'Erwachsene'
};
