/* Klassiker: die besten Denkaufgaben, Rechenkunststücke und Wissensschätze
   aus über hundert Jahren. Bewusst anspruchsvoll – nicht durch Vereinfachung
   entschärft, sondern durch eine Tippleiter: Wer allein draufkommt, bekommt
   mehr; wer nicht weiterkommt, bekommt Schritt für Schritt einen Anstoß.
   Zu jeder Aufgabe gehört ihre Herkunft – Rätsel haben eine Geschichte. */

/* ------------------------------ Knacknüsse ------------------------------ */
export const KNACKNUESSE = [
  { id:'wolf', frage:'Ein Bauer will Wolf, Ziege und Kohlkopf über einen Fluss bringen.\nIm Boot ist nur Platz für ihn und eine Sache.\nAllein gelassen frisst der Wolf die Ziege, die Ziege den Kohl.\nWas nimmt er als Erstes mit?',
    optionen:['die Ziege','den Wolf','den Kohlkopf','egal, welches'], antwort:'die Ziege',
    tipps:['Überlege, welche zwei am Ufer nicht allein bleiben dürfen.',
           'Wolf und Kohl vertragen sich – die Ziege ist bei beiden das Problem.'],
    quelle:'Aufgabensammlung von Alkuin, um 800 n. Chr.', stufe:1 },

  { id:'gauss', frage:'Zähle alle Zahlen von 1 bis 100 zusammen.\nEs geht in wenigen Sekunden – ohne hundert Additionen.',
    antwort:'5050',
    tipps:['Schreibe die Reihe zweimal untereinander – einmal vorwärts, einmal rückwärts.',
           '1+100 = 101, 2+99 = 101 … Wie viele solcher Paare gibt es?',
           '50 Paare zu je 101.'],
    quelle:'Der Überlieferung nach löste der junge Carl Friedrich Gauß diese Schulaufgabe um 1785 in Sekunden.', stufe:2 },

  { id:'muetzen', frage:'Drei Kinder stehen hintereinander und tragen Mützen: 2 rote und 3 blaue sind im Spiel.\nJedes sieht nur die Mützen vor sich. Das hinterste sieht zwei Mützen und sagt: „Ich weiß es nicht.“\nDas mittlere sieht eine Mütze und sagt: „Ich weiß es auch nicht.“\nDa sagt das vorderste, das gar nichts sieht: „Dann weiß ich, welche ich trage.“\nWelche Farbe hat seine Mütze?',
    optionen:['blau','rot','das ist nicht entscheidbar','beides möglich'], antwort:'blau',
    tipps:['Was hätte das hinterste Kind gesehen, wenn es sofort Bescheid gewusst hätte?',
           'Wüsste es sofort, hätte es zweimal Rot gesehen – also sind vorn nicht zwei rote Mützen.',
           'Das mittlere Kind weiß das auch. Hätte es vorn Rot gesehen, wüsste es nun seine eigene Farbe.'],
    quelle:'Klassiker der Logikrätsel, verbreitet seit dem 19. Jahrhundert.', stufe:4 },

  { id:'hanoi', frage:'Türme von Hanoi: 3 Scheiben liegen der Größe nach auf einem Stab.\nDu darfst immer nur eine Scheibe umlegen und nie eine größere auf eine kleinere.\nWie viele Züge brauchst du mindestens, um alle auf einen anderen Stab zu bringen?',
    antwort:'7',
    tipps:['Probiere es zuerst mit 1 Scheibe (1 Zug) und mit 2 Scheiben (3 Züge).',
           'Bei jeder weiteren Scheibe verdoppelt sich die Zahl und eins kommt dazu.',
           '1, 3, 7, 15 … die Formel ist 2 hoch n minus 1.'],
    quelle:'Édouard Lucas, 1883 – als Spiel „Tour de Hanoï“ verkauft.', stufe:3 },

  { id:'brueder', frage:'„Brüder und Schwestern habe ich keine, aber der Vater dieses Mannes ist der Sohn meines Vaters.“\nWer ist der Mann auf dem Bild?',
    optionen:['mein Sohn','ich selbst','mein Vater','mein Neffe'], antwort:'mein Sohn',
    tipps:['Löse den Satz von hinten auf: „der Sohn meines Vaters“ – wer ist das, wenn ich keine Geschwister habe?',
           'Der Sohn meines Vaters bin ich. Also: Der Vater dieses Mannes bin ich.'],
    quelle:'Englisches Volksrätsel, seit dem 19. Jahrhundert überliefert.', stufe:3 },

  { id:'schnecke', frage:'Eine Schnecke sitzt in einem 10 m tiefen Brunnen.\nAm Tag kriecht sie 3 m hoch, in der Nacht rutscht sie 2 m zurück.\nAn welchem Tag ist sie oben?',
    antwort:'8',
    tipps:['Pro Tag und Nacht kommt sie 1 m voran – aber achte auf den letzten Tag.',
           'Am Ende von Tag 7 ist sie bei 7 m. Was passiert an Tag 8?'],
    quelle:'Rechenbuchklassiker, u. a. bei Adam Ries im 16. Jahrhundert.', stufe:2 },

  { id:'muenzen', frage:'Du hast 8 gleich aussehende Münzen. Eine ist leichter als die anderen.\nDu hast eine Balkenwaage. Wie oft musst du mindestens wiegen, um die falsche sicher zu finden?',
    antwort:'2',
    tipps:['Teile nicht in zwei Hälften, sondern in drei Gruppen.',
           'Lege 3 gegen 3. Zwei Ausgänge: gleich schwer – oder eine Seite steigt.'],
    quelle:'Wiegeprobleme dieser Art kursierten in den 1940er-Jahren in ganz Europa.', stufe:4 },

  { id:'send', frage:'Buchstabenrechnen: Jeder Buchstabe steht für eine Ziffer.\n  SEND\n+ MORE\n= MONEY\nWelche Ziffer ist M?',
    optionen:['1','0','9','8'], antwort:'1',
    tipps:['MONEY hat eine Stelle mehr als SEND und MORE.',
           'Zwei vierstellige Zahlen ergeben höchstens knapp 20000.'],
    quelle:'Henry Dudeney, 1924 – die berühmteste Rechenaufgabe mit Buchstaben.', stufe:4 },

  { id:'kerzen', frage:'In einem Zimmer brennen 7 Kerzen. Ein Windstoß löscht 2 davon,\nspäter löscht er noch eine dritte. Die Fenster werden geschlossen.\nWie viele Kerzen sind am nächsten Morgen noch da?',
    optionen:['3','4','7','0'], antwort:'3',
    tipps:['Die brennenden Kerzen brennen die Nacht über ab.',
           'Nur was gelöscht wurde, bleibt übrig.'],
    quelle:'Altes Scherzrätsel, in vielen Sprachen überliefert.', stufe:2 },

  { id:'bruecken', frage:'In Königsberg lagen 7 Brücken über den Fluss.\nDie Frage der Bürger: Kann man einen Spaziergang machen,\nbei dem man jede Brücke genau einmal überquert?',
    optionen:['Nein, das ist unmöglich','Ja, aber nur sonntags','Ja, mit dem richtigen Startpunkt','Nur wenn man eine Brücke auslässt'],
    antwort:'Nein, das ist unmöglich',
    tipps:['Zähle, wie viele Brücken an jedem Ufer zusammenkommen.',
           'Wer ein Ufer betritt, muss es auch wieder verlassen – dafür braucht es Brücken in Paaren.'],
    quelle:'Leonhard Euler bewies 1736, dass es unmöglich ist – die Geburtsstunde der Graphentheorie.', stufe:4 },

  { id:'fibonacci', frage:'Ein Kaninchenpaar bekommt ab dem zweiten Monat jeden Monat ein neues Paar,\nund jedes neue Paar tut ab seinem zweiten Monat dasselbe.\nDie Paare pro Monat: 1, 1, 2, 3, 5, 8, ?\nWie geht es weiter?',
    antwort:'13',
    tipps:['Schau dir immer zwei benachbarte Zahlen an.',
           'Jede Zahl ist die Summe der beiden davor.'],
    quelle:'Leonardo Fibonacci, „Liber Abaci“, 1202.', stufe:2 },

  { id:'zwei_tueren', frage:'Zwei Türen, zwei Wächter. Eine Tür führt in die Freiheit, die andere nicht.\nEin Wächter lügt immer, einer sagt immer die Wahrheit – du weißt nicht, wer wer ist.\nDu darfst EINE Frage stellen. Welche?',
    optionen:['„Welche Tür würde der andere mir zeigen?“ – dann die andere nehmen',
              '„Bist du der Lügner?“','„Ist die linke Tür die richtige?“','„Wie viel Uhr ist es?“'],
    antwort:'„Welche Tür würde der andere mir zeigen?“ – dann die andere nehmen',
    tipps:['Suche eine Frage, deren Antwort bei beiden Wächtern gleich ausfällt.',
           'Wenn die Frage über den jeweils anderen geht, wird aus Wahrheit Lüge und aus Lüge Wahrheit.'],
    quelle:'Bekannt geworden durch Raymond Smullyan und den Film „Die Reise ins Labyrinth“ (1986).', stufe:5 },

  { id:'nim', frage:'Nim-Spiel: 12 Streichhölzer liegen auf dem Tisch.\nAbwechselnd nimmt jeder 1, 2 oder 3 Hölzer. Wer das letzte nimmt, gewinnt.\nDu darfst anfangen. Wie viele nimmst du?',
    optionen:['keins – wer anfängt, verliert bei richtigem Gegenspiel','1','2','3'],
    antwort:'keins – wer anfängt, verliert bei richtigem Gegenspiel',
    tipps:['Wie viele Hölzer möchtest du deinem Gegner hinterlassen, damit er nicht gewinnen kann?',
           'Günstig sind Vielfache von 4 – denn was er nimmt, ergänzt du auf 4.',
           '12 ist bereits ein Vielfaches von 4 – wer hier ziehen muss, ist im Nachteil.'],
    quelle:'Charles Bouton beschrieb die Gewinnstrategie 1901 mathematisch vollständig.', stufe:5 },

  { id:'ziegen', frage:'Drei Türen: hinter einer ein Auto, hinter zweien eine Ziege.\nDu wählst Tür 1. Der Moderator, der weiß, wo das Auto steht, öffnet Tür 3 – eine Ziege.\nEr fragt: Willst du wechseln?',
    optionen:['Ja, wechseln – die Gewinnchance steigt auf 2/3','Nein, egal – 50:50','Nein, bleiben ist besser','Man kann es nicht wissen'],
    antwort:'Ja, wechseln – die Gewinnchance steigt auf 2/3',
    tipps:['Wie hoch war die Chance, gleich beim ersten Griff richtig zu liegen?',
           'Die 1/3 deiner ersten Wahl ändert sich nicht. Die restlichen 2/3 stecken nun in einer einzigen Tür.'],
    quelle:'1975 von Steve Selvin beschrieben, 1990 durch Marilyn vos Savant weltberühmt – und heftig bestritten.', stufe:5 },

  { id:'zebra', frage:'In fünf Häusern wohnen fünf Nachbarn mit fünf Getränken.\nDer Norweger wohnt im ersten Haus. Der in der Mitte trinkt Milch.\nWer trinkt Milch?',
    optionen:['der Bewohner des dritten Hauses','der Norweger','der Bewohner des ersten Hauses','das ist offen'],
    antwort:'der Bewohner des dritten Hauses',
    tipps:['„In der Mitte“ von fünf Häusern – das wievielte ist das?'],
    quelle:'Aus dem „Zebrarätsel“, erstmals 1962 veröffentlicht. Es wird oft Einstein zugeschrieben – dafür gibt es keinen Beleg.', stufe:2 },

  { id:'handschlag', frage:'Auf einer Feier sind 10 Menschen. Jeder gibt jedem genau einmal die Hand.\nWie viele Handschläge sind das insgesamt?',
    antwort:'45',
    tipps:['Jeder gibt 9 anderen die Hand – das wären 90.',
           'Aber jeder Handschlag wurde dabei doppelt gezählt.'],
    quelle:'Standardaufgabe der Kombinatorik, seit dem 18. Jahrhundert in Lehrbüchern.', stufe:3 },

  { id:'wasser', frage:'Du hast einen 3-Liter- und einen 5-Liter-Krug, sonst nichts.\nWie misst du genau 4 Liter ab?\nWie oft musst du dafür mindestens umfüllen oder füllen? (Anzahl der Schritte)',
    antwort:'6',
    tipps:['Fülle den 5er, gieße daraus den 3er voll – was bleibt im 5er?',
           '5 füllen, 3 abfüllen (2 bleiben), 3er leeren, die 2 hinüber, 5er füllen, 3er auffüllen – der 5er hat dann 4.'],
    quelle:'Bekannt aus dem 16. Jahrhundert, weltberühmt durch den Film „Stirb langsam 3“ (1995).', stufe:4 },

  { id:'uhr', frage:'Wie oft überholt der Minutenzeiger den Stundenzeiger zwischen 12 Uhr mittags und 12 Uhr nachts?',
    optionen:['11','12','10','24'], antwort:'11',
    tipps:['Man könnte 12 vermuten – aber prüfe, wann es das erste Mal passiert.',
           'Kurz nach 1, kurz nach 2 … aber zwischen 11 und 12 fällt eines aus.'],
    quelle:'Klassische Uhrenaufgabe, u. a. bei Sam Loyd um 1900.', stufe:5 },

  { id:'seil', frage:'Zwei Schnüre brennen jeweils genau 60 Minuten ab – aber ungleichmäßig.\nWie misst du damit 45 Minuten?\nWie viele Enden zündest du zu Beginn an?',
    optionen:['3','2','1','4'], antwort:'3',
    tipps:['Zündest du eine Schnur an beiden Enden an, ist sie nach 30 Minuten weg.',
           'Erste Schnur an beiden Enden, zweite nur an einem – das sind 3 Enden.'],
    quelle:'Verbreitet in Einstellungstests seit den 1950er-Jahren.', stufe:5 },

  { id:'muehle', frage:'Ein Müller nimmt für jeden Sack Mehl, den er mahlt, ein Zehntel als Lohn.\nEin Bauer will nach dem Mahlen genau 9 Sack behalten.\nWie viele Sack Korn muss er bringen?',
    antwort:'10',
    tipps:['Vom Gebrachten bleibt ihm neun Zehntel.',
           'Neun Zehntel von wie viel ergibt 9?'],
    quelle:'Aus alten deutschen Rechenbüchern, 17. Jahrhundert.', stufe:3 },

  { id:'vier_farben', frage:'Wie viele Farben braucht man höchstens, um jede Landkarte so zu färben,\ndass keine zwei benachbarten Länder dieselbe Farbe haben?',
    optionen:['4','3','5','6'], antwort:'4',
    tipps:['Probiere es an einer Karte mit vielen Ländern – kommst du je über vier hinaus?'],
    quelle:'1852 vermutet, erst 1976 von Appel und Haken bewiesen – der erste große Beweis mit Computerhilfe.', stufe:3 },

  { id:'monat', frage:'Ein Seerosenblatt verdoppelt seine Fläche jeden Tag.\nNach 30 Tagen ist der Teich ganz bedeckt.\nAn welchem Tag war er halb bedeckt?',
    antwort:'29',
    tipps:['Gehe vom Ende her rückwärts.',
           'Wenn es sich täglich verdoppelt: Was war am Tag davor?'],
    quelle:'Klassisches Beispiel für exponentielles Wachstum, seit den 1970er-Jahren in Schulbüchern.', stufe:3 },

  { id:'zug', frage:'Zwei Züge fahren aufeinander zu: einer 60 km/h, einer 40 km/h, Abstand 100 km.\nEine Fliege fliegt mit 80 km/h zwischen ihnen hin und her, bis sie sich treffen.\nWie viele Kilometer legt die Fliege zurück?',
    antwort:'80',
    tipps:['Frage nicht nach dem Hin und Her – frage nach der Zeit.',
           'Die Züge nähern sich mit 100 km/h, brauchen also 1 Stunde.'],
    quelle:'Der Mathematiker John von Neumann soll die Aufgabe in Sekunden gelöst haben – durch Aufsummieren der unendlichen Reihe.', stufe:4 },

  { id:'socken', frage:'In einer dunklen Schublade liegen 10 schwarze und 10 blaue Socken.\nWie viele musst du herausnehmen, um sicher ein gleichfarbiges Paar zu haben?',
    optionen:['3','2','11','10'], antwort:'3',
    tipps:['Denke an den ungünstigsten Fall.',
           'Zwei Socken können verschiedenfarbig sein – die dritte muss zu einer passen.'],
    quelle:'Schubfachprinzip, formuliert von Dirichlet um 1834.', stufe:2 }
];

/* --------------------- Wissenskanon: was bleibt --------------------- */
export const KANON = [
  { bereich:'Entdeckungen', q:'Wer entdeckte 1928 durch Zufall das Penicillin?',
    ok:'Alexander Fleming', bad:['Louis Pasteur','Robert Koch','Marie Curie'],
    notiz:'Ein Schimmelpilz war in seine Bakterienschale geraten – der Beginn der Antibiotika.' },
  { bereich:'Entdeckungen', q:'Welche Forscherin erhielt als erster Mensch zwei Nobelpreise in zwei Fächern?',
    ok:'Marie Curie', bad:['Lise Meitner','Rosalind Franklin','Ada Lovelace'],
    notiz:'Physik 1903, Chemie 1911. Bis heute schaffte das kein zweiter Mensch.' },
  { bereich:'Entdeckungen', q:'Was entdeckte Wilhelm Conrad Röntgen 1895?',
    ok:'eine Strahlung, die durch Körper hindurchgeht', bad:['das Radio','den Impfstoff','das Radium'],
    notiz:'Er nannte sie X-Strahlen, weil er ihre Natur nicht kannte.' },
  { bereich:'Entdeckungen', q:'Was beschrieben Watson, Crick und Franklin 1953?',
    ok:'den Aufbau der DNA als Doppelhelix', bad:['die Erdumlaufbahn','das Atom','die Zellteilung'],
    notiz:'Rosalind Franklins Röntgenbild war entscheidend – sie wurde lange kaum genannt.' },
  { bereich:'Technik', q:'In welchem Jahr betraten zum ersten Mal Menschen den Mond?',
    ok:'1969', bad:['1957','1961','1972'], notiz:'Apollo 11, am 20. Juli 1969.' },
  { bereich:'Technik', q:'Wer flog 1963 als erste Frau ins All?',
    ok:'Walentina Tereschkowa', bad:['Sally Ride','Christa McAuliffe','Helen Sharman'],
    notiz:'Sie umrundete die Erde 48 Mal.' },
  { bereich:'Technik', q:'Was erfand Johannes Gutenberg um 1450?',
    ok:'den Buchdruck mit beweglichen Lettern', bad:['das Papier','die Brille','die Tinte'],
    notiz:'Erstmals konnten Bücher vervielfältigt werden – Wissen wurde für viele erreichbar.' },
  { bereich:'Technik', q:'Wofür ist Alan Turing berühmt?',
    ok:'Er legte die Grundlagen des Computers und entschlüsselte im Krieg Geheimcodes',
    bad:['Er erfand das Telefon','Er baute das erste Auto','Er entdeckte die Elektrizität'],
    notiz:'Seine Arbeit an der Enigma verkürzte den Zweiten Weltkrieg vermutlich um Jahre.' },
  { bereich:'Erde', q:'Wer erreichte 1953 als Erste den Gipfel des Mount Everest?',
    ok:'Edmund Hillary und Tenzing Norgay', bad:['Reinhold Messner','Roald Amundsen','Ernest Shackleton'],
    notiz:'Beide betonten zeitlebens, sie seien gemeinsam oben angekommen.' },
  { bereich:'Erde', q:'Wer erreichte 1911 als Erster den Südpol?',
    ok:'Roald Amundsen', bad:['Robert Falcon Scott','James Cook','Fridtjof Nansen'],
    notiz:'Scott kam fünf Wochen später an und starb auf dem Rückweg.' },
  { bereich:'Erde', q:'Welcher Fluss ist der längste Europas?',
    ok:'die Wolga', bad:['die Donau','der Rhein','die Elbe'], notiz:'Rund 3530 km, sie mündet ins Kaspische Meer.' },
  { bereich:'Erde', q:'Wie viele Ozeane hat die Erde nach heutiger Zählung?',
    ok:'5', bad:['3','4','7'], notiz:'Seit 2000 zählt auch der Südliche Ozean dazu.' },
  { bereich:'Geschichte', q:'Was geschah 1989 in Berlin?',
    ok:'Die Mauer fiel', bad:['Die Mauer wurde gebaut','Der Reichstag brannte','Die Stadt wurde gegründet'],
    notiz:'Am 9. November 1989 öffneten sich die Grenzübergänge.' },
  { bereich:'Geschichte', q:'Wie lange dauerte der Zweite Weltkrieg?',
    ok:'von 1939 bis 1945', bad:['von 1914 bis 1918','von 1933 bis 1945','von 1945 bis 1949'], notiz:'Sechs Jahre.' },
  { bereich:'Geschichte', q:'Wer war Nelson Mandela?',
    ok:'Er kämpfte gegen die Rassentrennung und wurde Präsident Südafrikas',
    bad:['ein Erfinder aus England','ein Feldherr der Antike','ein Komponist'],
    notiz:'27 Jahre im Gefängnis, 1994 zum Präsidenten gewählt.' },
  { bereich:'Kunst', q:'Wer schrieb „Pippi Langstrumpf“?',
    ok:'Astrid Lindgren', bad:['Erich Kästner','Michael Ende','Otfried Preußler'],
    notiz:'1945 erschienen – für ihre kranke Tochter erfunden.' },
  { bereich:'Kunst', q:'Wer komponierte die „Kleine Nachtmusik“?',
    ok:'Wolfgang Amadeus Mozart', bad:['Ludwig van Beethoven','Johann Sebastian Bach','Joseph Haydn'], notiz:'1787 entstanden.' },
  { bereich:'Kunst', q:'Wer malte die „Mona Lisa“?',
    ok:'Leonardo da Vinci', bad:['Michelangelo','Raffael','Vincent van Gogh'],
    notiz:'Er arbeitete jahrelang daran und gab das Bild nie ab.' },
  { bereich:'Kunst', q:'Wer schrieb „Die unendliche Geschichte“?',
    ok:'Michael Ende', bad:['Astrid Lindgren','Cornelia Funke','James Krüss'], notiz:'1979 erschienen.' },
  { bereich:'Natur', q:'Warum sind Bienen für uns Menschen so wichtig?',
    ok:'Sie bestäuben viele Pflanzen, aus denen unser Essen wächst',
    bad:['Sie machen den Boden fruchtbar','Sie vertreiben Schädlinge','Sie reinigen die Luft'],
    notiz:'Etwa ein Drittel unserer Nahrung hängt an bestäubenden Insekten.' },
  { bereich:'Natur', q:'Wie alt kann ein Baum wie die Eiche werden?',
    ok:'über 800 Jahre', bad:['etwa 50 Jahre','etwa 100 Jahre','etwa 200 Jahre'],
    notiz:'Einzelne Exemplare in Europa sind über 1000 Jahre alt.' },
  { bereich:'Natur', q:'Was passiert bei der Fotosynthese?',
    ok:'Die Pflanze macht aus Licht, Wasser und Kohlendioxid Zucker und Sauerstoff',
    bad:['Die Pflanze schläft','Die Pflanze nimmt Erde auf','Die Pflanze verliert Wasser'],
    notiz:'Praktisch aller Sauerstoff der Luft stammt daher.' },
  { bereich:'Zahlen', q:'Was ist eine Primzahl?',
    ok:'Eine Zahl, die nur durch 1 und sich selbst teilbar ist',
    bad:['Eine gerade Zahl','Eine Zahl über 100','Eine Zahl mit Komma'],
    notiz:'Euklid bewies vor 2300 Jahren: Es gibt unendlich viele davon.' },
  { bereich:'Zahlen', q:'Wofür steht die Kreiszahl π (Pi) ungefähr?',
    ok:'3,14', bad:['2,71','1,61','3,41'], notiz:'Sie gibt an, wie oft der Durchmesser in den Umfang passt.' },
  { bereich:'Zahlen', q:'Was besagt der Satz des Pythagoras?',
    ok:'Im rechtwinkligen Dreieck ist a² + b² = c²', bad:['Alle Winkel sind gleich','Der Umfang ist 2πr','Die Summe der Winkel ist 360°'],
    notiz:'Er war schon den Babyloniern tausend Jahre vor Pythagoras bekannt.' },
  { bereich:'Sprache', q:'Aus welcher Sprache stammen die meisten Fremdwörter der Wissenschaft?',
    ok:'Latein und Griechisch', bad:['Französisch','Arabisch','Englisch'],
    notiz:'„Telefon“ etwa heißt wörtlich „Fernklang“.' },
  { bereich:'Sprache', q:'Was ist ein Palindrom?',
    ok:'Ein Wort, das vorwärts wie rückwärts gleich ist', bad:['Ein sehr langes Wort','Ein Wort ohne Vokale','Ein Reimwort'],
    notiz:'„Otto“, „Rentner“, „Reliefpfeiler“.' }
];

/* -------------------- Redewendungen und ihre Herkunft -------------------- */
export const REDEWENDUNGEN = [
  { q:'„Etwas auf die lange Bank schieben“ bedeutet …', ok:'etwas immer wieder aufschieben',
    bad:['etwas gemeinsam tragen','etwas gut verstecken','sich ausruhen'],
    herkunft:'Vor Gericht wurden Akten früher in einer langen Truhe – der „Bank“ – abgelegt.' },
  { q:'„Ins Fettnäpfchen treten“ bedeutet …', ok:'aus Versehen etwas Unpassendes sagen',
    bad:['sehr gierig essen','Glück haben','sich schmutzig machen'],
    herkunft:'Vor Bauernhäusern stand ein Napf mit Fett zum Einfetten der Stiefel – wer ihn umstieß, ärgerte die Hausfrau.' },
  { q:'„Die Daumen drücken“ bedeutet …', ok:'jemandem Glück wünschen',
    bad:['streng sein','sich anstrengen','warten müssen'],
    herkunft:'Ein alter Aberglaube: Der eingeschlossene Daumen sollte böse Geister bannen.' },
  { q:'„Etwas aus dem Ärmel schütteln“ bedeutet …', ok:'etwas mühelos können',
    bad:['etwas verlieren','etwas verstecken','sich beschweren'],
    herkunft:'Die weiten Ärmel früherer Gewänder dienten als Taschen – daraus kam scheinbar mühelos alles hervor.' },
  { q:'„Jemandem einen Bären aufbinden“ bedeutet …', ok:'jemandem etwas Unwahres erzählen',
    bad:['jemandem helfen','jemanden erschrecken','jemanden loben'],
    herkunft:'Vermutlich von „bar“ – einer alten Bezeichnung für eine Last oder Abgabe, die man jemandem aufbürdet.' },
  { q:'„Alles in Butter“ bedeutet …', ok:'alles ist in Ordnung',
    bad:['alles ist teuer','alles ist verschmutzt','alles ist neu'],
    herkunft:'Zerbrechliches Gut wurde früher in flüssige Butter gelegt, die erstarrte und es beim Transport schützte.' },
  { q:'„Das ist nicht mein Bier“ bedeutet …', ok:'dafür bin ich nicht zuständig',
    bad:['das schmeckt mir nicht','das ist zu teuer','das mag ich nicht'],
    herkunft:'Vermutlich von „Bier“ als altem Wort für Angelegenheit oder Sache.' },
  { q:'„Perlen vor die Säue werfen“ bedeutet …', ok:'etwas Wertvolles an jemanden geben, der es nicht schätzt',
    bad:['Geld verschwenden','sehr großzügig sein','Tiere gut versorgen'],
    herkunft:'Aus der Bergpredigt im Matthäusevangelium.' },
  { q:'„Der Groschen ist gefallen“ bedeutet …', ok:'jemand hat es endlich verstanden',
    bad:['jemand hat Geld verloren','etwas ist heruntergefallen','jemand ist arm geworden'],
    herkunft:'Automaten funktionierten erst, wenn die Münze wirklich durchgefallen war.' },
  { q:'„Auf dem Holzweg sein“ bedeutet …', ok:'sich irren', bad:['im Wald spazieren','langsam sein','arm sein'],
    herkunft:'Holzwege im Wald enden dort, wo das Holz lag – wer ihnen folgte, kam nirgends an.' },
  { q:'„Etwas verschlimmbessern“ bedeutet …', ok:'etwas beim Verbessern schlechter machen',
    bad:['etwas gründlich reparieren','sich verbessern','etwas loben'],
    herkunft:'Ein Kunstwort, das schon im 17. Jahrhundert belegt ist.' },
  { q:'„Über den Tellerrand schauen“ bedeutet …', ok:'auch das Größere und Fremde in den Blick nehmen',
    bad:['unhöflich essen','neugierig auf Nachbarn sein','sich beschweren'],
    herkunft:'Wer nur auf seinen Teller sieht, bemerkt nicht, was um ihn herum geschieht.' }
];

/* ---------------- Rechenkunststücke: alte Kopfrechen-Tricks ---------------- */
export const RECHENTRICKS = [
  { id:'elf',    name:'Mal 11 im Kopf',
    erklaerung:'Bei zweistelligen Zahlen: Ziffern auseinanderziehen, ihre Summe in die Mitte. 34 × 11 → 3 (3+4) 4 → 374.',
    quelle:'Aus Rechenbüchern des 19. Jahrhunderts, später im System Trachtenberg.' },
  { id:'fuenf',  name:'Quadrat von Zahlen auf 5',
    erklaerung:'Die Zehnerziffer mal ihren Nachfolger, dann 25 anhängen. 35² → 3 × 4 = 12 → 1225.',
    quelle:'Bereits bei arabischen Rechenmeistern des Mittelalters bekannt.' },
  { id:'gauss',  name:'Gauß-Summe',
    erklaerung:'1 + 2 + … + n = n × (n+1) ÷ 2. Man paart die Zahlen von außen nach innen.',
    quelle:'Der Überlieferung nach von Gauß als Schuljunge wiederentdeckt.' },
  { id:'neuner', name:'Die Neunerprobe',
    erklaerung:'Quersummen verraten Rechenfehler: Stimmt die Quersumme des Ergebnisses nicht, ist etwas falsch.',
    quelle:'Seit dem Mittelalter der Standardtest der Kaufleute – lange vor dem Taschenrechner.' },
  { id:'bauern', name:'Russische Bauernmultiplikation',
    erklaerung:'Eine Zahl halbieren, die andere verdoppeln – Zeilen mit gerader linker Zahl streichen, den Rest addieren.',
    quelle:'Schon im alten Ägypten verwendet, in Russland bis ins 20. Jahrhundert gebräuchlich.' },
  { id:'prozent',name:'Prozente im Kopf',
    erklaerung:'10 % ist das Komma um eine Stelle nach links. 5 % ist die Hälfte davon, 20 % das Doppelte.',
    quelle:'Kaufmännisches Grundwissen seit Jahrhunderten.' }
];
